language: java
jdk:
- openjdk8
script: mvn clean verify
deploy:
  provider: heroku
  api_key:
    secure: CsAzhQdTLwbFg/Q5v95mOiWEtTuIHWTWRYDK+nVNZ1O3M+fPnU7YZVBaOPWc5AoVglicDSdSMcc8Uv/HZcaGH1Zx87lmu1icbcUduOS5BzlK+XsJqQiFIkoZZ6hQWRMm4LYTRNgVUKTKdIpQa8HmmuvOWYT1aEPnYtYOIYeKb6A5vGR8hZvSlssDAaQDDM8LPgsynJbH27re1jBQAtbJceEA+MsTn+aozb9gX8ZjEA3rWIsZUz6C6InJ89qx3fAqjkUNQybvdlY8BDtakZtn0tlr2gcCD43PO3E4O5GxZYCP6Ku1IR7v+ayWT03MrH1HuHz4SYcFeF3OLMK3Az/R7Rg/g4iMOgzjCDGMW8sJGsqBx8CDd8iLwVsBV54cm+SlW9unPt67z1Yw0uGooZJfye3KIQY3pGeKEzUvTRkCCn7+t0CgNCiMrwmRqG4EaQS728C03WQctH5nGP2U7Pl9T17UF5uJsP/cRnqTualH7upULnwGPfuwtm2U1Rhd2f0ExfGbAji9tkybZCeZ/qrxSCZiEPmItU9iuJAOGQemnfd679MGKgsa3Vm5Au+WHKlBHEQFzIZtFL377q+waeMKYtOXAuGKNaAcPb2f+PyO57i0ukAGPidzMO3WJSbwQK6iu68yKjed4IjjoVZgCt8QDOIHDCipwBzi44Z6+vl3qag=
