language: java
jdk:
- openjdk8
script: mvn clean verify
deploy:
  provider: heroku
  api_key:
    secure: kSSxb3+BGon/WX8onUcjr7ipITJTdt9esG2j3QoG1JS4HOJitPISiJsL37jSqw9++VjUQyJi2/5UditkPfHcmnlmY/hlTiz39goy8ILv/y7DByuY7gI4bW0002DRSvvpGIuw/QNnBwYcmC60z0cLD0OrG3RzskCxu5Le+AE/8OBbpI5rrKwUcJlAt010zWbHc0wJqqjyyXsptllhe/3VIkWOW9z4RlOB5zfRQ343R4/QiEVJPt/IhPYd42N7ixrT1QAYRbP1pyQ4uGs5KAnnZlGNe8VTsW0tM8VDmmgDZoDnDc/mw8+vnlw8BlQ9Yi1n+OwAhDcOAPgS/hVwa9uMAmRLJscJeJNBTlpnLo0CxyNFNIxdvPgldEMxsV43FpiIFHBrg3lzn7maPWPpJx8JDA+KbbttOhMRnVYeIzflfGwod1wg+0Z1kcwAaVLJ2d3yWLvPrQInxQKSNp3ygd6a0JZwGmXFT64pRdn/h9ptQ/Xyq1hQimn9lNyxMgK9GI+mxZgADp1PKUOXDKfseMQWJY+njKlHw4jNmTJMHrfpBAqM9LmjdBWYAYk2dWaRf2x4ythmm3M/r4+eC9p5CfzHkHPVVofbHr8G79pbwV1MFBvzvzzKU50hHHOBCF9ANz0VCIvTN09I4M5aqQcKDPVt0bSmkoH7upNrsiKFLIN0BOI=
